ui:
  hideHeader: true
  hideFooter: true
  showFileTree: true
  fileTreeWidth: 30
  searchTreeWidth: 50
  icons: nerd-fonts-filetype
  colorFileNames: true
  showDiffStats: true
  sideBySide: true
  startFoldersOpenDepth: -1
  theme: catppuccin_mocha
