#!/bin/sh

# You have to press Ctrl-x to send the next key to the external key-handler
while read file
do
	case "$1" in
  	"C-d") trash-put "$file" ;; # depends on trash-cli
    "C-r") convert -rotate 90 "$file" "$file" ;;
    "C-c") echo -n "$file" | xclip -selection clipboard ;;
    "C-w") xwallpaper --center "$file" ;;
  esac
done
