# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# True color support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides "xterm-256color:Tc"

# Start index of window/pane to 1, because we're humans, not computers
set -g base-index 1
setw -g pane-base-index 1

# Options
set -g mouse on
set -g status-position top
set -g focus-events on # update files on focus (useful for vim)
set -s escape-time 0 # instantly exit to normal mode on vim 

# Reload config file (change file location to your the tmux.conf you want to use)
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Set vim keybindings
set-window-option -g mode-keys vi

# Use vim copy mode (and copy to the clipboard)
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Makes mouse selection intuitive
unbind -T copy-mode-vi MouseDragEnd1Pane

# Split pane horizontally using \ and vertically using --
bind-key - split-window -v  -c '#{pane_current_path}'
bind-key \\ split-window -h  -c '#{pane_current_path}'
bind = select-layout even-horizontal

# Vim-like pane switching
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Toggle opencode or claude
bind o popup -E -d "#{pane_current_path}" -w 90% -h 90% "claude --continue"

# Status bar theme
set -g status on
set -g status-interval 2
set -g status-justify centre
set -g status-style "bg=default,fg=default"
set -g status-left "#[bg=default,fg=default,bold]#{?client_prefix,#[fg=#9ece6a],}  #S #[bg=default,fg=default]"
set -g status-right ""
set -g window-status-format " #I:#W "
set -g window-status-current-format "#[fg=#ff9e64][#[bg=default,fg=default]#I:#W#[fg=#ff9e64,bg=default]]"

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persists tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions every 15 minutes
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin '27medkamal/tmux-session-wizard'

# Configure plugins
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
