[mgr]
ratio          = [ 1, 2, 5 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "size"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 1920
max_height      = 1080
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75

[opener]
edit = [
	{ run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$1"',                desc = "Open", for = "linux" },
	{ run = 'open "$@"',                    desc = "Open", for = "macos" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$1")"',           desc = "Reveal", for = "linux" },
	{ run = 'open -R "$1"',                         desc = "Reveal", for = "macos" },
	{ run = '''clear; exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "linux" },
	{ run = 'open -na iina.app "$@"', orphan = true, for = "macos" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[plugin]
prepend_previewers = [
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.txt", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
  { url = "*.ipynb", run = "rich-preview"},
]

prepend_preloaders = [
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.txt", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false }
]

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "normal"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "normal"

