music_directory     "/Volumes/Media Library/Music"
playlist_directory  "/Volumes/Media Library/Music/Playlists"
db_file             "~/.config/mpd/database"
state_file          "~/.config/mpd/state"

follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

bind_to_address "localhost"
port            "6600"
restore_paused  "true"

audio_output {
	type "osx"
	name "Mac Studio"
}

audio_output {
    type        "httpd"
    name        "Icecast Stream"
    encoder     "lame"
    port        "8000"
    bitrate     "320"
    format      "44100:16:2"
}

