#!/bin/sh

#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|

#
# autostart
#
picom &
dunst &
unclutter &
xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &
${HOME}/.config/polybar/launch.sh &
xrdb merge ${XDG_CONFIG_HOME:-$HOME/.config}/X11/xresources &
${HOME}/.local/bin/setbg &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xautolock -time 10 -locker "i3lock-fancy --nofork -f Hack-Regular-Nerd-Font-Complete" &

pgrep -x pamac-tray > /dev/null || pamac-tray &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x jetbrains-toolb > /dev/null || jetbrains-toolbox &
pgrep -x owncloud > /dev/null || owncloud &
pgrep -x insync > /dev/null || insync start &

wmname LG3D

# change keyboard layout
setxkbmap -model pc104 -layout us,gr -option grp:alt_shift_toggle

#
# monitors
#
bspc monitor -d "1 " "2 " "3 " "4 " "5 " "6 " "7 " "8 " "9 " "0 " 

#
# bspwm configuration
#
bspc config border_radius         				8
bspc config border_width          				2
bspc config window_gap           					10

bspc config top_padding           				20
bspc config bottom_padding        				0
bspc config left_padding          				0
bspc config right_padding         				0

bspc config split_ratio          					0.55

bspc config single_monocle                false
bspc config borderless_monocle   					true
bspc config gapless_monocle      					true

bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config pointer_modifier 							mod4
bspc config pointer_action1 							move
bspc config pointer_action2 							resize_side
bspc config pointer_action3 							resize_corner

#
# bspwm colors 
#
bspc config normal_border_color		      	"#4c566a"
bspc config active_border_color	        	"#ebcb8b"
bspc config focused_border_color	      	"#5e81ac"
bspc config presel_feedback_color	      	"#5e81ac"
bspc config urgent_border_color 	      	"#bf616a"


#
# bspwm rules
#
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Thunderbird desktop='^4' follow=on
bspc rule -a mpv state=fullscreen
bspc rule -a Gnome-calculator state=floating
